# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('total_length', models.CharField(max_length=10)),
                ('del_time', models.CharField(max_length=10)),
                ('start_area', models.CharField(max_length=10)),
                ('end_area', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
    ]
