# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_area', models.CharField(max_length=5)),
                ('end_area', models.CharField(max_length=5)),
                ('method', models.CharField(max_length=5)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
