# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.CharField(max_length=10)),
                ('end_x', models.CharField(max_length=10)),
                ('recommend_x', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
