# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_deliverydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverydata',
            old_name='deli_time',
            new_name='del_time',
        ),
    ]
