# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171030_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydata',
            name='del_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='deliverydata',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='deliverydata',
            name='total_length',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='deliverydata',
            name='weight',
            field=models.CharField(max_length=10),
        ),
    ]
